import type { ChecklistPriority } from "@/lib/domain/types";

export interface ChecklistSeedItem {
  area: string;
  category: string;
  title: string;
  description: string;
  captureGuide: string;
  requiredPhotoCount: number;
  priority: ChecklistPriority;
}

export const DEFAULT_AREAS: string[] = [
  "현관",
  "거실",
  "주방",
  "공용욕실",
  "침실 1",
  "침실 2",
  "안방",
  "안방욕실",
  "발코니",
  "다용도실",
  "전기·통신",
  "기타",
];

export const CHECKLIST_SEED: ChecklistSeedItem[] = [
  {
    area: "현관",
    category: "문/창호",
    title: "현관문 개폐 및 문틀 상태",
    description:
      "현관문이 부드럽게 열리고 닫히는지, 문틀과 간섭이 없는지, 도장 찍힘이나 틈새가 없는지 확인한다.",
    captureGuide: "현관문 전체 1장, 문틀 틈새 1장, 손상 부위 근접 1장.",
    requiredPhotoCount: 2,
    priority: "HIGH",
  },
  {
    area: "현관",
    category: "바닥/타일",
    title: "현관 바닥 타일 및 줄눈 상태",
    description: "타일 깨짐, 들뜸, 줄눈 누락, 오염, 단차를 확인한다.",
    captureGuide: "현관 바닥 전체와 의심 타일 근접 사진.",
    requiredPhotoCount: 2,
    priority: "MEDIUM",
  },
  {
    area: "현관",
    category: "전기",
    title: "센서등·도어락 작동",
    description: "센서등 점등, 도어락 잠금/해제, 흔들림 여부를 확인한다.",
    captureGuide: "점등 상태 + 도어락 외관.",
    requiredPhotoCount: 1,
    priority: "MEDIUM",
  },
  {
    area: "거실",
    category: "바닥",
    title: "거실 마루 찍힘·들뜸·벌어짐",
    description: "마루 표면 손상, 들뜸, 벌어진 틈, 보행 시 소음을 확인한다.",
    captureGuide: "거실 바닥 전체 1장과 손상 부위 근접 1장.",
    requiredPhotoCount: 2,
    priority: "MEDIUM",
  },
  {
    area: "거실",
    category: "창호",
    title: "거실 창호 개폐 및 코킹",
    description: "개폐, 잠금, 유리 기스, 방충망, 코킹 상태를 확인한다.",
    captureGuide: "닫힌 상태 / 열린 상태 / 잠금부 / 코킹 근접.",
    requiredPhotoCount: 3,
    priority: "HIGH",
  },
  {
    area: "거실",
    category: "마감",
    title: "벽지·천장 마감 상태",
    description: "도배 들뜸, 찢김, 이음부 벌어짐, 천장 균열·얼룩을 확인한다.",
    captureGuide: "벽 전체 1장 + 의심 부위 근접.",
    requiredPhotoCount: 2,
    priority: "MEDIUM",
  },
  {
    area: "주방",
    category: "급배수",
    title: "싱크대 수전 및 배수 누수 확인",
    description:
      "물을 틀어 수압, 냉온수 전환, 배수 속도, 하부장 누수를 확인한다.",
    captureGuide: "수전 작동 상태 1장, 싱크대 하부 배관 1장.",
    requiredPhotoCount: 2,
    priority: "HIGH",
  },
  {
    area: "주방",
    category: "수납",
    title: "상부장·하부장 문짝 수평",
    description: "문 수평, 경첩 작동, 내부 마감 상태를 확인한다.",
    captureGuide: "전체 닫힘 1장 + 내부 1장.",
    requiredPhotoCount: 2,
    priority: "MEDIUM",
  },
  {
    area: "주방",
    category: "마감",
    title: "주방 타일 및 후드 상태",
    description: "타일 깨짐·들뜸·줄눈, 후드 작동·조명을 확인한다.",
    captureGuide: "타일 전체 + 후드 작동 상태.",
    requiredPhotoCount: 2,
    priority: "MEDIUM",
  },
  {
    area: "공용욕실",
    category: "방수/배수",
    title: "공용욕실 바닥 구배 및 배수",
    description: "물을 흘려 배수구 방향으로 잘 빠지는지, 물 고임을 확인한다.",
    captureGuide: "물 흐름 + 배수구 주변.",
    requiredPhotoCount: 2,
    priority: "HIGH",
  },
  {
    area: "공용욕실",
    category: "타일",
    title: "공용욕실 벽·바닥 타일",
    description: "타일 깨짐, 들뜸, 줄눈 불량, 오염을 확인한다.",
    captureGuide: "전체 1장 + 의심 타일 근접.",
    requiredPhotoCount: 2,
    priority: "HIGH",
  },
  {
    area: "공용욕실",
    category: "위생도기",
    title: "세면대·변기·샤워기 작동",
    description: "균열, 고정 불량, 누수, 배수, 수압을 확인한다.",
    captureGuide: "세면대 하부 + 변기 설치부 + 샤워기 작동.",
    requiredPhotoCount: 3,
    priority: "HIGH",
  },
  {
    area: "침실 1",
    category: "창호",
    title: "침실 1 창문·잠금·방충망",
    description: "창문 개폐, 잠금장치, 방충망 찢김, 코킹 상태를 확인한다.",
    captureGuide: "창 전체 / 잠금부 / 방충망 / 코킹.",
    requiredPhotoCount: 3,
    priority: "MEDIUM",
  },
  {
    area: "침실 1",
    category: "마감",
    title: "침실 1 벽·바닥 마감",
    description: "도배 이음, 마루 찍힘, 콘센트 작동을 확인한다.",
    captureGuide: "벽 전체 + 바닥 손상 + 콘센트.",
    requiredPhotoCount: 2,
    priority: "MEDIUM",
  },
  {
    area: "침실 2",
    category: "창호",
    title: "침실 2 창문·잠금·방충망",
    description: "창문 개폐, 잠금장치, 방충망, 코킹 상태를 확인한다.",
    captureGuide: "창 전체 / 잠금부 / 방충망 / 코킹.",
    requiredPhotoCount: 3,
    priority: "MEDIUM",
  },
  {
    area: "침실 2",
    category: "마감",
    title: "침실 2 벽·바닥 마감",
    description: "도배 이음, 마루 찍힘, 콘센트 작동을 확인한다.",
    captureGuide: "벽 전체 + 바닥 손상 + 콘센트.",
    requiredPhotoCount: 2,
    priority: "MEDIUM",
  },
  {
    area: "안방",
    category: "수납",
    title: "안방 붙박이장 문짝 수평",
    description: "문짝 수평, 경첩, 선반 고정을 확인한다.",
    captureGuide: "외부 닫힘 + 내부.",
    requiredPhotoCount: 2,
    priority: "MEDIUM",
  },
  {
    area: "안방",
    category: "창호",
    title: "안방 창문·잠금·방충망",
    description: "창문 개폐, 잠금, 방충망, 코킹 상태를 확인한다.",
    captureGuide: "창 전체 / 잠금부 / 방충망 / 코킹.",
    requiredPhotoCount: 3,
    priority: "MEDIUM",
  },
  {
    area: "안방욕실",
    category: "방수/배수",
    title: "안방욕실 바닥 구배 및 배수",
    description: "물 흐름, 배수 속도, 고임 여부를 확인한다.",
    captureGuide: "물 흐름 + 배수구.",
    requiredPhotoCount: 2,
    priority: "HIGH",
  },
  {
    area: "안방욕실",
    category: "실리콘",
    title: "샤워부스·욕조 실리콘 마감",
    description: "벌어짐, 누락, 충진 불량, 곰팡이 흔적을 확인한다.",
    captureGuide: "전체 + 의심 부위 근접 2장.",
    requiredPhotoCount: 3,
    priority: "HIGH",
  },
  {
    area: "안방욕실",
    category: "환기",
    title: "환풍기 작동 및 천장 점검구",
    description: "환풍기 작동음, 흡입력, 점검구 마감을 확인한다.",
    captureGuide: "환풍기 + 천장 점검구.",
    requiredPhotoCount: 2,
    priority: "MEDIUM",
  },
  {
    area: "발코니",
    category: "배수",
    title: "발코니 배수 및 바닥 구배",
    description: "배수구 주변 물 고임, 바닥 경사, 타일 상태를 확인한다.",
    captureGuide: "물 흐름 테스트 후 배수구 + 고임 부위.",
    requiredPhotoCount: 2,
    priority: "HIGH",
  },
  {
    area: "발코니",
    category: "안전",
    title: "발코니 난간 흔들림",
    description: "난간 고정 상태, 흔들림, 도장 상태를 확인한다.",
    captureGuide: "난간 전체 + 고정부 근접.",
    requiredPhotoCount: 2,
    priority: "CRITICAL",
  },
  {
    area: "다용도실",
    category: "설비",
    title: "보일러·분배기 누수",
    description: "보일러, 분배기, 밸브, 배관 연결부의 누수와 마감을 확인한다.",
    captureGuide: "전체 + 밸브 + 배관 연결부.",
    requiredPhotoCount: 3,
    priority: "CRITICAL",
  },
  {
    area: "다용도실",
    category: "급배수",
    title: "세탁 수전·배수",
    description: "세탁 수전 누수, 배수 속도, 악취·역류 여부를 확인한다.",
    captureGuide: "수전 작동 + 배수구.",
    requiredPhotoCount: 2,
    priority: "HIGH",
  },
  {
    area: "전기·통신",
    category: "전기",
    title: "분전반·차단기·콘센트 통전",
    description: "분전반 표시, 차단기 작동, 주요 콘센트 통전을 확인한다.",
    captureGuide: "분전반 전체 + 콘센트 테스트 메모.",
    requiredPhotoCount: 2,
    priority: "HIGH",
  },
  {
    area: "전기·통신",
    category: "통신",
    title: "인터폰·월패드·화재감지기",
    description: "인터폰·월패드 작동, 화재감지기 위치·파손을 확인한다.",
    captureGuide: "월패드 화면 + 화재감지기.",
    requiredPhotoCount: 2,
    priority: "MEDIUM",
  },
];
